// data.js
const data = [
  {
    id: 1,
    name: "Project 1",
    category: "Software & SaaS",
    imageUrl: "https://example.com/image1.jpg",
    pageType: "Landing Page",
    deviceType: "Desktop",
  },
  {
    id: 2,
    name: "Project 2",
    category: "Software & SaaS",
    imageUrl: "https://example.com/image2.jpg",
    pageType: "Pricing Page",
    deviceType: "Mobile",
  },
  {
    id: 3,
    name: "Project 3",
    category: "Software & SaaS",
    imageUrl: "https://example.com/image3.jpg",
    pageType: "About Page",
    deviceType: "Desktop",
  },
  {
    id: 4,
    name: "Project 4",
    category: "AI",
    imageUrl: "https://example.com/image4.jpg",
    pageType: "Landing Page",
    deviceType: "Mobile",
  },
  {
    id: 5,
    name: "Project 5",
    category: "AI",
    imageUrl: "https://example.com/image5.jpg",
    pageType: "Pricing Page",
    deviceType: "Desktop",
  },
  {
    id: 6,
    name: "Project 6",
    category: "AI",
    imageUrl: "https://example.com/image6.jpg",
    pageType: "About Page",
    deviceType: "Mobile",
  },
  {
    id: 7,
    name: "Project 7",
    category: "Fintech",
    imageUrl: "https://example.com/image7.jpg",
    pageType: "Landing Page",
    deviceType: "Desktop",
  },
  {
    id: 8,
    name: "Project 8",
    category: "Fintech",
    imageUrl: "https://example.com/image8.jpg",
    pageType: "Pricing Page",
    deviceType: "Mobile",
  },
  {
    id: 9,
    name: "Project 9",
    category: "Fintech",
    imageUrl: "https://example.com/image9.jpg",
    pageType: "About Page",
    deviceType: "Desktop",
  },
  {
    id: 10,
    name: "Project 10",
    category: "Agency & Corporate",
    imageUrl: "https://example.com/image10.jpg",
    pageType: "Landing Page",
    deviceType: "Mobile",
  },
  {
    id: 11,
    name: "Project 11",
    category: "Agency & Corporate",
    imageUrl: "https://example.com/image11.jpg",
    pageType: "Pricing Page",
    deviceType: "Desktop",
  },
  {
    id: 12,
    name: "Project 12",
    category: "Agency & Corporate",
    imageUrl: "https://example.com/image12.jpg",
    pageType: "About Page",
    deviceType: "Mobile",
  },
  {
    id: 13,
    name: "Project 13",
    category: "E-Commerce",
    imageUrl: "https://example.com/image13.jpg",
    pageType: "Landing Page",
    deviceType: "Desktop",
  },
  {
    id: 14,
    name: "Project 14",
    category: "E-Commerce",
    imageUrl: "https://example.com/image14.jpg",
    pageType: "Pricing Page",
    deviceType: "Mobile",
  },
  {
    id: 15,
    name: "Project 15",
    category: "E-Commerce",
    imageUrl: "https://example.com/image15.jpg",
    pageType: "About Page",
    deviceType: "Desktop",
  },
  {
    id: 16,
    name: "Project 16",
    category: "Crypto & Web3",
    imageUrl: "https://example.com/image16.jpg",
    pageType: "Landing Page",
    deviceType: "Mobile",
  },
  {
    id: 17,
    name: "Project 17",
    category: "Crypto & Web3",
    imageUrl: "https://example.com/image17.jpg",
    pageType: "Pricing Page",
    deviceType: "Desktop",
  },
  {
    id: 18,
    name: "Project 18",
    category: "Crypto & Web3",
    imageUrl: "https://example.com/image18.jpg",
    pageType: "About Page",
    deviceType: "Mobile",
  },
  {
    id: 19,
    name: "Project 19",
    category: "Travel & Hospitality",
    imageUrl: "https://example.com/image19.jpg",
    pageType: "Landing Page",
    deviceType: "Desktop",
  },
  {
    id: 20,
    name: "Project 20",
    category: "Travel & Hospitality",
    imageUrl: "https://example.com/image20.jpg",
    pageType: "Pricing Page",
    deviceType: "Mobile",
  },
  {
    id: 21,
    name: "Project 21",
    category: "Travel & Hospitality",
    imageUrl: "https://example.com/image21.jpg",
    pageType: "About Page",
    deviceType: "Desktop",
  },
  {
    id: 22,
    name: "Project 22",
    category: "Software & SaaS",
    imageUrl: "https://example.com/image22.jpg",
    pageType: "Landing Page",
    deviceType: "Mobile",
  },
  {
    id: 23,
    name: "Project 23",
    category: "Software & SaaS",
    imageUrl: "https://example.com/image23.jpg",
    pageType: "Pricing Page",
    deviceType: "Desktop",
  },
  {
    id: 24,
    name: "Project 24",
    category: "Software & SaaS",
    imageUrl: "https://example.com/image24.jpg",
    pageType: "About Page",
    deviceType: "Mobile",
  },
  {
    id: 25,
    name: "Project 25",
    category: "AI",
    imageUrl: "https://example.com/image25.jpg",
    pageType: "Landing Page",
    deviceType: "Desktop",
  },
  {
    id: 26,
    name: "Project 26",
    category: "AI",
    imageUrl: "https://example.com/image26.jpg",
    pageType: "Pricing Page",
    deviceType: "Mobile",
  },
  {
    id: 27,
    name: "Project 27",
    category: "AI",
    imageUrl: "https://example.com/image27.jpg",
    pageType: "About Page",
    deviceType: "Desktop",
  },
  {
    id: 28,
    name: "Project 28",
    category: "Travel & Hospitality",
    imageUrl: "https://example.com/image28.jpg",
    pageType: "404 Page",
    deviceType: "Mobile",
  },
  {
    id: 29,
    name: "Project 29",
    category: "Travel & Hospitality",
    imageUrl: "https://example.com/image29.jpg",
    pageType: "Login Page",
    deviceType: "Desktop",
  },
  {
    id: 30,
    name: "Project 30",
    category: "Travel & Hospitality",
    imageUrl: "https://example.com/image30.jpg",
    pageType: "Pricing Page",
    deviceType: "Mobile",
  },
];

export default data;
